<?php
 
 
   //$query_share = $this->chart_query('2021-09-14','2021-09-14',);
   $data_action = 'https://www.googleapis.com/analytics/v3/data/ga?access_token='.$this->access_token .'&ids='.$this->ga_id.'&dimensions=ga%3AsocialNetwork&metrics=ga%3Apageviews&start-date='.$action_chart_tab['dates'][0].'&end-date='.$action_chart_tab['dates'][1].'';

 

   $cURLConnection = curl_init();

      curl_setopt($cURLConnection, CURLOPT_URL, $data_action );
      curl_setopt($cURLConnection, CURLOPT_RETURNTRANSFER, true);

      $phoneList = curl_exec($cURLConnection);
      curl_close($cURLConnection);

      $jsonArrayResponse = json_decode($phoneList);

     

 
 ?>
<div class="analytics-action">
   <?php 

      if(!empty($jsonArrayResponse->rows)){
         $index =0;
         foreach($jsonArrayResponse->rows as  $val){
            
         ?>
            <div name="<?php echo $val[0]?>" index="<?php echo $index;?>" class="trending-number <?php echo ($index==0)?'active':'';?> clickable-number ng-scope ng-isolate-scope selected-trending-number" ng-repeat="action in $ctrl.state.results track by" filter="number">
      <!-- ngIf: ::goal.description -->
            <h4 class="trending-number-title ng-binding">Share <?php echo $val[0]?></h4>
            <div class="actions-count-wrapper">
               <div>
                  <span class="count ng-binding"><?php echo $val[1]?></span>
                  <span class="label">actions</span>
               </div>
               <!-- ngIf: ::goal.value -->
               <div class="segment-chart missing-value" ng-class="::{'missing-value': !goal.value }">
                  <div class="pie-chart">
                     <div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;">
                        <div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                           <div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div>
                        </div>
                        <div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                           <div style="position:absolute;width:200%;height:200%;left:0; top:0"></div>
                        </div>
                     </div>
                     <canvas width="90" height="90" class="chartjs-render-monitor-<?php echo $index ;?>" style="display: block; box-sizing: border-box; height: 60px; width: 60px;"></canvas>
                  </div>
                  <div class="chart-label" tooltip="0 out of 0">
                     <span class="percentage ng-binding">
                     99%
                     </span>
                     generated by content
                  </div>
               </div>
               <!-- ngIf: goal.url -->
            </div>
         </div>
         <script>
            var ctx = jQuery(".chartjs-render-monitor-<?php echo $index ;?>");
               var myChart = new Chart(ctx, {
                 type: 'pie',
                 data: {
                   //labels: ["Green", "Blue", "Gray", "Purple", "Yellow", "Red", "Black"],
                   datasets: [{
                     backgroundColor: [
                       "#4ec3c8",
                        
                     ],
                     data: [<?php echo $val[1]?>]
                   }]
                 }
               });
         </script>
         <?php 

            $index ++;
         
         }
      }

 

   ?>
   

 </div>
<div class="social-chart">
	<div class="social-chart-head">
		<h4 class="wrapper-graph-heading ng-binding">Submit Popup Subscribe Form</h4>
		<div class="pillbox-toggle-container">
		   <div class="pillbox-toggle"><button class="active ">Daily</button><button class="">Weekly</button><button class="">Monthly</button></div>
		   <div class="pillbox-toggle"></div>
		</div>
	</div>
   <div class="chart-wrap">
    <canvas id="chart-area-0"></canvas>
   </div>
</div>

<script>
 

   jQuery('.clickable-number').click(function (event){
       event.preventDefault();
       jQuery('.clickable-number').removeClass('active');
       jQuery(this).addClass('active');
        var index = jQuery(this).attr('index');
       var name = jQuery(this).attr('name');
       var date = jQuery('input.daterange').val();
       var prevdate = jQuery('input#compare-range-picker').val();
       var date = jQuery('input.daterange').val();
         var split = date.split('to');
         var start = split[0];
         var end = split[1];

         jQuery.ajax({
                  dataType: "json", 
                 type : "GET",
                 url : ajaxurl,
                 data : {action: "action_chart",name:name,start:start,end:end,prevdate:prevdate},
                 success: function(response) {
                    jQuery('.chart_amount').val(response);   
                    jQuery('.chart-wrap').html('<canvas id="chart-area-'+index+'"></canvas>');
                    action_chart(response['daterange'],response['rangevalue'],response['prevdata'],index);
                    console.log(response);
                }
          }); 

   });

action_chart(<?php echo json_encode($action_chart_tab['daterange']); ?>,<?php echo json_encode($action_chart_tab['rangevalue']); ?>,<?php echo json_encode($action_chart_tab['prevdata']); ?>,0);
function action_chart(rangedate,current,prevdata,index){
   
      var config = {
        type: 'line',
        data: {
        labels:rangedate,
        datasets: [{
            align: 'start',
            label: 'Previous Period',
            data:prevdata,
            backgroundColor: '#ffffff0a',
  
            borderColor: 'rgba(210, 210, 210,1)',

        },{
            align: 'start',
            label: 'Current Period ',
            data: current,
            backgroundColor:'#ffffff0a',
            borderColor:'rgba(78 ,195 ,200,1)',
 
        }]
    },
        options: {
            responsive: true,
            plugins: {
            legend: {
              position: 'right',
            },
            title: {
              display: true,
            }
          }
        }
    };
   var ctx = document.getElementById('chart-area-'+index).getContext('2d');
   window.myPie = new Chart(ctx, config);

}  

</script>